# Generated by Django 4.2 on 2023-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_message_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin')], default='', max_length=20),
        ),
    ]
