# Generated by Django 4.2 on 2023-12-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
