# Generated by Django 4.2 on 2023-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_remove_message_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sendername',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
