# Generated by Django 4.2 on 2023-12-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_sendername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sendername',
        ),
    ]
