# Generated by Django 4.2 on 2023-12-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_message_remove_chatroom_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='admins',
            new_name='admin',
        ),
    ]
