# Generated by Django 4.2 on 2023-12-16 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_rename_admins_chat_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admin',
            field=models.ManyToManyField(related_name='admin_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
