# Generated by Django 4.2 on 2023-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_remove_roomimage_image_roomimage_imagee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='imagee',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='media/images/'),
        ),
    ]
