# Generated by Django 4.2 on 2023-12-04 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_app', '0008_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='media/room_images'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('room', 'customer')},
        ),
    ]
