# Generated by Django 4.2 on 2023-12-05 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_alter_roombooking_room_alter_roombooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
