# Generated by Django 4.2 on 2023-12-07 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0011_roombooking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='check_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_out',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
