# Generated by Django 4.2 on 2023-12-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0013_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(upload_to='media/media/images'),
        ),
    ]
